# Generated by Django 4.2.23 on 2025-09-01 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0002_quotevote'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='type_of_source',
            field=models.CharField(choices=[('film', 'Фильм'), ('book', 'Книга'), ('game', 'Игра'), ('series', 'Сериал'), ('comic', 'Комикс')], default='film', max_length=20),
        ),
    ]
