# Generated by Django 4.2.23 on 2025-09-02 05:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0003_quote_type_of_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotevote',
            name='quote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='quotes.quote'),
        ),
    ]
