# Generated by Django 4.2.23 on 2025-09-02 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0005_quote_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='movie_link',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Ссылка на фильм'),
        ),
    ]
