# Generated by Django 4.2.23 on 2025-09-03 03:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0006_quote_movie_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotevote',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='quote',
            name='text',
            field=models.TextField(error_messages={'unique': 'Такая цитата уже существует.'}, unique=True),
        ),
    ]
